update

diff --git a/.github/workflows/aws_git-fetch.yml b/.github/workflows/aws_git-fetch.yml
--- a/.github/workflows/aws_git-fetch.yml
+++ b/.github/workflows/aws_git-fetch.yml
@@ -28,7 +28,15 @@ jobs:
             git merge origin/master
 
             sudo docker compose down
-            sudo docker compose up --build --abort-on-container-exit --exit-code-from test test #* This will cause the GitHub Action to fail if the Test fails. Notice how we are not using "-d". We DO NEED to use -d below
+            sudo docker compose up --build --abort-on-container-exit --exit-code-from test test 
+
+            #* Handling docker-test errors
+            EXIT_CODE=$? #$ This captures the exit code of the last command.
+            if [ $EXIT_CODE -ne 0 ]; then #$ "-ne" means "not equal"
+              echo "Test container failed with exit code $EXIT_CODE"
+              exit $EXIT_CODE #$ This exits the ENTIRE GitHub Action with the same exit code.
+            fi
+            
             sudo docker compose up --build -d 
 
 
